type profile = {
  id: string;
  username: string;
  email: string;
  country?: string;
  education_level_id?: number;
  likeddeckids?: string[];
  followedcreators?: string[];
  purchaseddeckids?: string[];
  purchaseinfo?: { deckId: string; purchaseDate: string }[];
  followers?: string[];
  phone_number?: string;
  preferred_categories?: string[];
  class?: string;
  total_sales?: number;
  total_earnings?: number;
};

type decks = {
  id: "uuid"; // Auto-generated by Firestore
  title: "text";
  description: "text";
  price: "numeric";
  card_count: "integer";
  difficulty: "text";
  imageurl: "text";
  creatorid: "uuid"; // Reference to the user in the Profiles collection
  created_at: "timestamp";
  updated_at: "timestamp";
  flashcards_file_url: "text"; // URL to the file in Firebase Storage
  categories: ["array", "of", "strings"];
  creator_avatar: "text";
  cover_image_url: "text";
  purchase_history: ["array", "of", "objects"]; // Array of purchase objects
  average_rating: "numeric";
  total_reviews: "integer";
};

type reviews = {
  id: "uuid"; // Auto-generated by Firestore
  deck_id: "uuid"; // Reference to the deck in the Decks collection
  user_id: "uuid"; // Reference to the user in the Profiles collection
  rating: "integer";
  comment: "text";
  created_at: "timestamp";
  updated_at: "timestamp";
};
